#!/bin/bash

qsub -v U='0' -N NillL8U0 run_time_ev_test
qsub -v U='1' -N NillL8U1 run_time_ev_test
qsub -v U='2' -N NillL8U2 run_time_ev_test
qsub -v U='4' -N NillL8U4 run_time_ev_test
qsub -v U='6' -N NillL8U6 run_time_ev_test
qsub -v U='8' -N NillL8U8 run_time_ev_test



