#!/bin/bash

qsub -v cutoff='1E-10',L='4' -N SL4E10 run_stress_test
qsub -v cutoff='1E-10',L='8' -N SL8E10 run_stress_test
qsub -v cutoff='1E-10',L='12' -N SL12E10 run_stress_test
qsub -v cutoff='1E-10',L='16' -N SL16E10 run_stress_test
qsub -v cutoff='1E-10',L='20' -N SL20E10 run_stress_test
qsub -v cutoff='1E-10',L='24' -N SL24E10 run_stress_test
qsub -v cutoff='1E-10',L='28' -N SL28E10 run_stress_test
qsub -v cutoff='1E-10',L='32' -N SL32E10 run_stress_test
qsub -v cutoff='1E-10',L='36' -N SL36E10 run_stress_test
qsub -v cutoff='1E-10',L='40' -N SL40E10 run_stress_test
qsub -v cutoff='1E-10',L='44' -N SL44E10 run_stress_test
qsub -v cutoff='1E-10',L='48' -N SL48E10 run_stress_test
qsub -v cutoff='1E-10',L='52' -N SL52E10 run_stress_test
qsub -v cutoff='1E-10',L='56' -N SL56E10 run_stress_test
qsub -v cutoff='1E-10',L='60' -N SL60E10 run_stress_test

qsub -v cutoff='1E-12',L='4' -N SL4E12 run_stress_test
qsub -v cutoff='1E-12',L='8' -N SL8E12 run_stress_test
qsub -v cutoff='1E-12',L='12' -N SL12E12 run_stress_test
qsub -v cutoff='1E-12',L='16' -N SL16E12 run_stress_test
qsub -v cutoff='1E-12',L='20' -N SL20E12 run_stress_test
qsub -v cutoff='1E-12',L='24' -N SL24E12 run_stress_test
qsub -v cutoff='1E-12',L='28' -N SL28E12 run_stress_test
qsub -v cutoff='1E-12',L='32' -N SL32E12 run_stress_test
qsub -v cutoff='1E-12',L='36' -N SL36E12 run_stress_test
qsub -v cutoff='1E-12',L='40' -N SL40E12 run_stress_test
qsub -v cutoff='1E-12',L='44' -N SL44E12 run_stress_test
qsub -v cutoff='1E-12',L='48' -N SL48E12 run_stress_test
qsub -v cutoff='1E-12',L='52' -N SL52E12 run_stress_test
qsub -v cutoff='1E-12',L='56' -N SL56E12 run_stress_test
qsub -v cutoff='1E-12',L='60' -N SL60E12 run_stress_test




