#!/bin/bash

qsub -v U='0',L='20' -N L20U0E6 run_time_ev_test
qsub -v U='1',L='20' -N L20U1E6 run_time_ev_test
qsub -v U='4',L='20' -N L20U4E6 run_time_ev_test
qsub -v U='8',L='20' -N L20U8E6 run_time_ev_test

qsub -v U='0',L='40' -N L40U0E6 run_time_ev_test
qsub -v U='1',L='40' -N L40U1E6 run_time_ev_test
qsub -v U='4',L='40' -N L40U4E6 run_time_ev_test
qsub -v U='8',L='40' -N L40U8E6 run_time_ev_test

qsub -v U='0',L='80' -N L80U0E6 run_time_ev_test
qsub -v U='1',L='80' -N L80U1E6 run_time_ev_test
qsub -v U='4',L='80' -N L80U4E6 run_time_ev_test
qsub -v U='8',L='80' -N L80U8E6 run_time_ev_test



