#!/bin/bash

qsub -v U='0' -N L8U0 run_time_ev_test
qsub -v U='1' -N L8U1 run_time_ev_test
qsub -v U='2' -N L8U2 run_time_ev_test
qsub -v U='4' -N L8U4 run_time_ev_test
qsub -v U='6' -N L8U6 run_time_ev_test
qsub -v U='8' -N L8U8 run_time_ev_test



